anniuser= input("quanti anni hai?")
print()
annocorrente= input ("in che anno siamo?")
annonascita= int(annocorrente) - int(anniuser)
print()
print ("Anno di nascita:",annonascita)
print()
print()